-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 18:41:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wbasketball
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wbasketball
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wbasketball` DEFAULT CHARACTER SET utf8 ;
USE `wbasketball` ;

-- -----------------------------------------------------
-- Table `wbasketball`.`teams`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `wbasketball`.`teams` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(45) NOT NULL,
  `ranking` INT NOT NULL,
  PRIMARY KEY (`idTeam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wbasketball`.`matches`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `wbasketball`.`matches` (
  `idMatch` INT NOT NULL AUTO_INCREMENT,
  `idLocalTeam` INT NOT NULL,
  `idVisitorTeam` INT NOT NULL,
  `localPoints` INT NULL,
  `visitorPoints` INT NULL,
  `dateMatch` DATETIME NULL,
  PRIMARY KEY (`idMatch`, `idLocalTeam`, `idVisitorTeam`),
  CONSTRAINT `idLocalTeam`
    FOREIGN KEY (`idLocalTeam`)
    REFERENCES `wbasketball`.`teams` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idVisitorTeam`)
    REFERENCES `wbasketball`.`teams` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idLocalTeam_idx` ON `wbasketball`.`matches` (`idLocalTeam` ASC);

CREATE INDEX `idVisitorTeam_idx` ON `wbasketball`.`matches` (`idVisitorTeam` ASC);


-- -----------------------------------------------------
-- Table `wbasketball`.`players`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `wbasketball`.`players` (
  `idPlayer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `position` ENUM("base", "'escolta", "alero", "ala-pivot", "pivot") NOT NULL,
  `birthdate` DATETIME NOT NULL,
  `idTeam` INT NOT NULL,
  PRIMARY KEY (`idPlayer`, `idTeam`),
    FOREIGN KEY (`idTeam`)
    REFERENCES `wbasketball`.`teams` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idTeam_idx` ON `wbasketball`.`players` (`idTeam` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;